import type { Job, JobStoryChoice, JobStoryScene } from "../../../models/job";
import {
  maximumJobStoryChoiceDepth,
  minimumJobStoryChoiceDepth,
} from "../../../models/job";
import type { Player } from "../../../models/player";
import { createPlayerPromptContext } from "./createPlayerPromptContext";

export function createStoryBeatPrompt(
  player: Player,
  job: Job,
  story: JobStoryScene,
  choicePath: JobStoryChoice[],
  choice: JobStoryChoice,
): string {
  return [
    "Continue the job with the next playable story beat.",
    "",
    `PLAYER_CONTEXT=${JSON.stringify(createPlayerPromptContext(player))}`,
    `ENGINE_JOB=${JSON.stringify(job)}`,
    `CURRENT_SCENE=${JSON.stringify(story)}`,
    `CHOICE_PATH=${JSON.stringify(choicePath)}`,
    `PLAYER_CHOICE=${JSON.stringify(choice)}`,
    "",
    "Writing standards:",
    "- Show the immediate consequence of PLAYER_CHOICE through action, dialogue pressure, or a changed physical situation.",
    "- Pay off one concrete detail from CURRENT_SCENE, then introduce one new complication or opening.",
    "- Keep the prose clear, specific, and grounded. Avoid melodrama, recap-heavy narration, and generic crime phrasing.",
    "- Write exactly three scene sentences, each 8-18 words.",
    "- Use simple words and clear physical details the player can picture.",
    "- Each sentence should show what changes, what someone does, or what can go wrong.",
    "- Keep the stage map consistent, but mention only positions or details that changed.",
    "- Do not write the scene map as a checklist.",
    "- Do not repeat an action already completed in CURRENT_SCENE or CHOICE_PATH.",
    "- If you already have the target, make the next beat about escape, witnesses, or a new cost.",
    "- Add one meaningful new change. Do not restate the same threat in new words.",
    "- Use clear place words like gate, table, crates, door, alley, or office.",
    "- Avoid unclear poetic phrases, odd metaphors, compressed noir wording, and vague spaces.",
    "- Address the player as you. Do not use the player's name or nickname, even if CURRENT_SCENE does.",
    "- Use PLAYER_CONTEXT.loadout to shape what the player can try next.",
    "- If equipped gear is useful, let one choice naturally use it without forcing violence.",
    "- The player should feel that this beat only happened because of the selected path.",
    "",
    "Branching requirements:",
    `- This beat follows player decision ${choicePath.length}.`,
    `- Easy jobs may conclude after ${minimumJobStoryChoiceDepth}, 4, or ${maximumJobStoryChoiceDepth} choices.`,
    "- Because the API requested another beat, this scene must create a real new decision.",
    "- Return exactly two new choices for the next decision.",
    "- The two choices must create meaningfully different risks, not just different wording for the same tactic.",
    "- If the player has a knife, it can cut, pry, threaten, or help at close range.",
    "- Choice labels must be two to four simple words.",
    "- Choice intents must be one clear sentence under 12 words.",
    "- Risk hints must be under seven words and name a clear danger.",
    "- Choice text should read like fast UI copy, not prose.",
    "- Keep the job plausible for the player's low rank, current resources, and Docks location.",
    "",
    "Return this JSON shape:",
    JSON.stringify({
      choices: [
        {
          approach: "quiet",
          id: "quiet-next",
          intent: "Move closer behind the crates.",
          label: "Move Closer",
          riskHint: "Lookout may hear.",
        },
        {
          approach: "social",
          id: "social-next",
          intent: "Send the lookout toward the gate.",
          label: "Distract Him",
          riskHint: "He may shout.",
        },
      ],
      choiceDepth: choicePath.length,
      scene: "Exactly three clear sentences with one new material change.",
      stakes: "One clear sentence under 14 words.",
      title: "Short beat title.",
    }),
  ].join("\n");
}
