import {
  type ApiErrorCode,
  type ApiErrorDescriptor,
} from "../../../shared/apiError";
import type { PlayerLanguage } from "../../../shared/language";

const ERROR_MESSAGES: Record<
  PlayerLanguage,
  Record<ApiErrorCode, string>
> = {
  en: {
    active_job_exists: "Finish your current job first.",
    attack_cooldown: "Your crew is still regrouping. Wait before attacking again.",
    building_damaged: "Repair the building before upgrading it.",
    building_max_level: "That building is already fully upgraded.",
    building_not_damaged: "That building does not need repairs.",
    building_not_owned: "You do not own that building.",
    building_staff_limit: "That building's crew limit is {count}.",
    candidate_unavailable: "That candidate is no longer available.",
    conflict: "That action is not available right now.",
    crew_cannot_fire_on_job: "You cannot dismiss a crew member during a job.",
    crew_capacity: "Your leadership lets you bring up to {count} crew on this job.",
    crew_consumable_forbidden: "Crew members cannot equip consumable items.",
    crew_gear_confiscated: "{name}'s gear is being held as evidence.",
    crew_limit: "Your current crew limit is {count}.",
    crew_member_not_found: "Crew member {id} could not be found.",
    crew_not_free_to_fight: "{name} is not available to fight.",
    crew_not_free_for_job: "{name} is not available for a job.",
    crew_not_free_to_guard: "{name} is not available to stand guard.",
    crew_not_free_to_train: "{name} is not available to train right now.",
    crew_not_free_to_work: "{name} is not available to work there.",
    crew_not_imprisoned: "{name} is not in prison.",
    crew_on_job: "{name} is currently on a job.",
    crew_skill_max: "{name} has reached the maximum skill level.",
    crew_skill_required: "{name} needs skill level {required} to use that item.",
    duplicate_property: "You already own one of those properties.",
    family_exists: "Your family has already been founded.",
    family_name_taken: "Another family already uses that name.",
    family_protected: "That family is still protected from attacks.",
    family_required: "Found your family before doing that.",
    forbidden: "You cannot do that right now.",
    full_health: "You are already at full health.",
    heat_already_zero: "Your heat is already at zero.",
    insufficient_cash: "You need {amount} to do that.",
    insufficient_funds: "You do not have enough cash for that.",
    internal_error: "Something went wrong on the server. Try again.",
    invalid_auth_token: "Your session expired. Sign in again.",
    invalid_crew_equipment_slot: "Crew members can only carry a weapon, body armor, and a belt.",
    invalid_mission_choice: "That is not one of your available choices.",
    invalid_request: "Check the submitted information and try again.",
    item_not_equippable: "That item is used from the stash and cannot be equipped.",
    item_not_in_stash: "That item is not in your stash.",
    item_not_usable: "That item is equipment and cannot be used from the stash.",
    item_reserved: "That item is reserved for your active job.",
    job_board_changed: "The job board changed. Refresh it and choose again.",
    job_offer_unavailable: "That job is no longer on the board.",
    landmark_requires_attack: "Landmarks must be taken by force.",
    level_required: "You need to be level {required} to do that.",
    mission_gear_required: "You need {item} for that choice.",
    mission_item_unavailable: "{item} is no longer available for this choice.",
    mission_not_found: "That mission could not be found.",
    mission_resolved: "That job is already over.",
    no_active_job: "No job is currently in progress.",
    not_imprisoned: "You are not in prison.",
    own_turf: "You cannot attack your own turf.",
    player_not_found: "Player not found.",
    player_exists: "You already have a player.",
    player_imprisoned: "You cannot do that while you are in prison.",
    player_name_taken: "That player name is already taken.",
    precinct_unavailable_in_prison: "The precinct will not deal with you while you are in prison.",
    prison_attempt_cooldown: "The guards are watching too closely. Wait before trying again.",
    property_limit: "Your current property limit is {count}.",
    property_not_for_sale: "That property is not available on the market.",
    rate_limited: "Too many attempts. Wait a moment and try again.",
    rank_too_low: "Your rank is not high enough for that.",
    recruitment_locked: "Build your reputation before recruiting a crew.",
    recruitment_pool_empty: "There are no candidates available right now.",
    release_pending: "Your release is being processed. Refresh in a moment.",
    request_failed: "The request could not be completed.",
    required_fields: "Required request information is missing ({count} fields).",
    resource_not_found: "That could not be found.",
    racket_not_available: "That business cannot be built on turf.",
    route_not_found: "That server route does not exist.",
    slot_empty: "That equipment slot is already empty.",
    stamina_required: "You need {required} stamina to do that.",
    still_generating: "The next scene is still being prepared.",
    store_item_not_found: "The store does not carry that item.",
    territory_locked: "The city map unlocks when you become a Local Boss.",
    territory_required: "Claim territory of your own before attacking another family.",
    takeover_required: "Use a takeover to claim unoccupied turf.",
    turf_claimed: "That turf has already been claimed.",
    turf_full: "There is no room left to build on that turf.",
    turf_not_adjacent: "Expand from your territory one block at a time.",
    turf_not_found: "That turf could not be found.",
    turf_not_owned: "That turf does not belong to your family.",
    turf_shielded: "That turf is protected from attacks right now.",
    unauthenticated: "Sign in to continue.",
  },
  "pt-BR": {
    active_job_exists: "Termine seu trabalho atual primeiro.",
    attack_cooldown: "Sua equipe ainda está se reorganizando. Aguarde antes de atacar novamente.",
    building_damaged: "Conserte o negócio antes de melhorá-lo.",
    building_max_level: "Esse negócio já está no nível máximo.",
    building_not_damaged: "Esse negócio não precisa de reparos.",
    building_not_owned: "Você não é dono desse negócio.",
    building_staff_limit: "O limite de equipe desse negócio é {count}.",
    candidate_unavailable: "Esse candidato não está mais disponível.",
    conflict: "Essa ação não está disponível agora.",
    crew_cannot_fire_on_job: "Você não pode dispensar um membro da equipe durante um trabalho.",
    crew_capacity: "Sua liderança permite levar até {count} pessoas neste trabalho.",
    crew_consumable_forbidden: "Membros da equipe não podem equipar itens consumíveis.",
    crew_gear_confiscated: "O equipamento de {name} está retido como prova.",
    crew_limit: "Seu limite atual de equipe é {count}.",
    crew_member_not_found: "O membro da equipe {id} não foi encontrado.",
    crew_not_free_to_fight: "{name} não está disponível para lutar.",
    crew_not_free_for_job: "{name} não está disponível para um trabalho.",
    crew_not_free_to_guard: "{name} não está disponível para montar guarda.",
    crew_not_free_to_train: "{name} não está disponível para treinar agora.",
    crew_not_free_to_work: "{name} não está disponível para trabalhar ali.",
    crew_not_imprisoned: "{name} não está na prisão.",
    crew_on_job: "{name} está em um trabalho no momento.",
    crew_skill_max: "{name} atingiu o nível máximo de habilidade.",
    crew_skill_required: "{name} precisa ter habilidade no nível {required} para usar esse item.",
    duplicate_property: "Você já possui uma propriedade desse tipo.",
    family_exists: "Sua família já foi fundada.",
    family_name_taken: "Outra família já usa esse nome.",
    family_protected: "Essa família ainda está protegida contra ataques.",
    family_required: "Crie sua família antes de fazer isso.",
    forbidden: "Você não pode fazer isso agora.",
    full_health: "Sua saúde já está no máximo.",
    heat_already_zero: "Sua pressão já está zerada.",
    insufficient_cash: "Você precisa de {amount} para fazer isso.",
    insufficient_funds: "Você não tem dinheiro suficiente para isso.",
    internal_error: "Algo deu errado no servidor. Tente novamente.",
    invalid_auth_token: "Sua sessão expirou. Entre novamente.",
    invalid_crew_equipment_slot: "Membros da equipe só podem carregar uma arma, proteção para o corpo e um cinto.",
    invalid_mission_choice: "Essa não é uma das opções disponíveis.",
    invalid_request: "Confira as informações enviadas e tente novamente.",
    item_not_equippable: "Esse item é usado no esconderijo e não pode ser equipado.",
    item_not_in_stash: "Esse item não está no seu esconderijo.",
    item_not_usable: "Esse item é um equipamento e não pode ser usado no esconderijo.",
    item_reserved: "Esse item está reservado para o seu trabalho atual.",
    job_board_changed: "O quadro de trabalhos mudou. Atualize-o e escolha novamente.",
    job_offer_unavailable: "Esse trabalho não está mais no quadro.",
    landmark_requires_attack: "Pontos estratégicos precisam ser tomados à força.",
    level_required: "Você precisa estar no nível {required} para fazer isso.",
    mission_gear_required: "Você precisa do equipamento exigido para escolher essa opção.",
    mission_item_unavailable: "O equipamento exigido não está mais disponível para essa opção.",
    mission_not_found: "Esse trabalho não foi encontrado.",
    mission_resolved: "Esse trabalho já terminou.",
    no_active_job: "Não há nenhum trabalho em andamento.",
    not_imprisoned: "Você não está na prisão.",
    own_turf: "Você não pode atacar seu próprio território.",
    player_not_found: "Jogador não encontrado.",
    player_exists: "Você já criou um personagem.",
    player_imprisoned: "Você não pode fazer isso enquanto está na prisão.",
    player_name_taken: "Esse nome de jogador já está em uso.",
    precinct_unavailable_in_prison: "A delegacia não negocia com você enquanto está na prisão.",
    prison_attempt_cooldown: "Os guardas estão atentos demais. Aguarde antes de tentar novamente.",
    property_limit: "Seu limite atual de propriedades é {count}.",
    property_not_for_sale: "Essa propriedade não está disponível no mercado.",
    rate_limited: "Muitas tentativas. Aguarde um momento e tente novamente.",
    rank_too_low: "Seu cargo ainda não é alto o bastante para isso.",
    recruitment_locked: "Construa sua reputação antes de recrutar uma equipe.",
    recruitment_pool_empty: "Não há candidatos disponíveis agora.",
    release_pending: "Sua libertação está sendo processada. Atualize em instantes.",
    request_failed: "Não foi possível concluir a solicitação.",
    required_fields: "Faltam informações obrigatórias na solicitação ({count} campos).",
    resource_not_found: "Não foi possível encontrar isso.",
    racket_not_available: "Esse negócio não pode ser construído em um território.",
    route_not_found: "Essa rota do servidor não existe.",
    slot_empty: "Esse espaço de equipamento já está vazio.",
    stamina_required: "Você precisa de {required} de energia para fazer isso.",
    still_generating: "A próxima cena ainda está sendo preparada.",
    store_item_not_found: "A loja não vende esse item.",
    territory_locked: "O mapa da cidade é liberado quando você se torna Chefe Local.",
    territory_required: "Reivindique um território antes de atacar outra família.",
    takeover_required: "Use uma missão de tomada para reivindicar um território desocupado.",
    turf_claimed: "Esse território já foi reivindicado.",
    turf_full: "Não há espaço para construir nesse território.",
    turf_not_adjacent: "Expanda seu território um quarteirão por vez.",
    turf_not_found: "Esse território não foi encontrado.",
    turf_not_owned: "Esse território não pertence à sua família.",
    turf_shielded: "Esse território está protegido contra ataques agora.",
    unauthenticated: "Entre para continuar.",
  },
};

function formatParameter(
  key: string,
  value: string | number,
  language: PlayerLanguage,
): string {
  if (key === "amount" && typeof value === "number") {
    return new Intl.NumberFormat(language, {
      currency: "USD",
      maximumFractionDigits: 0,
      style: "currency",
    }).format(value);
  }

  if (key === "name" && language === "pt-BR" && typeof value === "string") {
    return value.replace(/ "[^"]+"/, "");
  }

  return String(value);
}

export function formatApiError(
  descriptor: ApiErrorDescriptor,
  language: PlayerLanguage,
): string {
  let message = ERROR_MESSAGES[language][descriptor.code];
  if (descriptor.params) {
    for (const [key, value] of Object.entries(descriptor.params)) {
      if (value !== undefined) {
        message = message.replaceAll(
          `{${key}}`,
          formatParameter(key, value, language),
        );
      }
    }
  }
  return message.replace(" {id}", "");
}
